// Keep the collection in one place. Add a local image under public/albums and
// set `cover` to (for example) '/albums/xingfu-de-pangbian.jpg' when available.
export const ALBUMS = [
  {
    id: 'xingfu-de-pangbian',
    title: '幸福的旁边',
    artist: '花儿乐队',
    year: 1999,
    edition: '新蜂音乐 · CD',
    cover: '/albums/xingfu-de-pangbian.jpg',
    accent: '#e63946',
    tracks: [
      '轰隆隆',
      '花',
      '四季歌 (新蜂版)',
      '向我开炮',
      '静止',
      '破灭',
      '起飞',
      '幸福的旁边',
      '稻草上的火鸡',
      '结果',
      '别骗我 (DEMO)',
      '融化',
      '没辙',
      '花 (木吉他版)',
      '放学啦 (新蜂版)',
      '歌唱 (CD版附送曲)',
    ],
  },
  {
    id: 'zhi-hu-zhe-ye',
    title: '之乎者也',
    artist: '羅大佑',
    year: 1982,
    edition: '滾石唱片 · LP',
    cover: '/albums/zhi-hu-zhe-ye.jpg',
    accent: '#c92328',
    tracks: [
      '鹿港小鎮',
      '戀曲1980',
      '童年',
      '錯誤',
      '搖籃曲',
      '之乎者也',
      '鄉愁四韻',
      '將進酒',
      '光陰的故事',
      '蒲公英',
    ],
  },
  {
    id: 'weilai-de-zhurenweng',
    title: '未來的主人翁',
    artist: '羅大佑',
    year: 1983,
    edition: '滾石唱片 · LP',
    cover: '/albums/weilai-de-zhurenweng.jpg',
    accent: '#afb58a',
    tracks: [
      '誕生',
      '亞細亞的孤兒',
      '現象七十二變',
      '牧童',
      '未來的主人翁',
      '青春舞曲',
      '愛的箴言',
      '小妹',
      '盲聾',
      '稻草人',
    ],
  },
  {
    id: 'queens-road-east',
    title: '皇后大道東',
    artist: '群星 · 音樂工廠',
    year: 1991,
    edition: '音樂工廠 · CD',
    cover: '/albums/queens-road-east.jpg',
    accent: '#b75939',
    tracks: [
      { title: '皇后大道東', artist: '羅大佑、蔣志光' },
      { title: '情深義更深', artist: '袁鳳瑫' },
      { title: '出走', artist: '夏韶聲' },
      { title: '赤子', artist: '葉德嫻' },
      { title: '長路有多遠', artist: '蔣志光' },
      { title: '似是故人來', artist: '梅艷芳' },
      { title: '天若有情', artist: '袁鳳瑫' },
      { title: '道', artist: '黃霅' },
      { title: '青春舞曲2000', artist: '羅大佑' },
      { title: '東方之珠', artist: '羅大佑' },
    ],
  },
  {
    id: 'hei-bao',
    title: '黑豹',
    artist: '黑豹樂隊',
    year: 1991,
    edition: '滾石唱片 · CD',
    cover: '/albums/hei-bao.jpg',
    accent: '#e25326',
    tracks: [
      '無地自容',
      'Take Care',
      '體會',
      '別來糾纏我',
      '靠近我',
      "Don't Break My Heart",
      '臉譜',
      '怕你為自己流淚',
      '眼光裡',
      '別去糟蹋',
    ],
  },
  {
    id: 'rock-china-power',
    title: '搖滾中國樂勢力',
    artist: '群星',
    year: 1995,
    edition: '魔岩唱片 · Live CD',
    cover: '/albums/rock-china-power.jpg',
    accent: '#e44b2d',
    tracks: [
      { title: '噢 乖', artist: '竇唯' },
      { title: '高級動物 (Live)', artist: '竇唯' },
      { title: '悲傷的夢 (Live)', artist: '竇唯' },
      { title: '飛翔鳥 (Live)', artist: '唐朝樂隊' },
      { title: '選擇 (Live)', artist: '唐朝樂隊' },
      { title: '孤獨的人是可恥的 (Live)', artist: '張楚' },
      { title: '廁所和床 (Live)', artist: '張楚' },
      { title: '蟞蟻 蟞蟻 (Live)', artist: '張楚' },
      { title: '姑娘 漂亮 (Live)', artist: '何勇' },
      { title: '鐘鼓樓 (Live)', artist: '何勇' },
    ],
  },
  {
    id: 'a-night-at-the-opera',
    title: 'A Night at the Opera',
    artist: 'Queen',
    year: 1975,
    edition: 'EMI · LP',
    cover: '/albums/a-night-at-the-opera.jpg',
    accent: '#8e1f2f',
    tracks: [
      'Death on Two Legs (Dedicated to…)',
      'Lazing on a Sunday Afternoon',
      "I'm in Love with My Car",
      "You're My Best Friend",
      "'39",
      'Sweet Lady',
      'Seaside Rendezvous',
      "The Prophet's Song",
      'Love of My Life',
      'Good Company',
      'Bohemian Rhapsody',
      'God Save the Queen',
    ],
  },
  {
    id: 'the-works',
    title: 'The Works',
    artist: 'Queen',
    year: 1984,
    edition: 'EMI · LP',
    cover: '/albums/the-works.jpg',
    accent: '#a51d25',
    tracks: [
      'Radio Ga Ga',
      'Tear It Up',
      "It's a Hard Life",
      'Man on the Prowl',
      "Machines (or 'Back to Humans')",
      'I Want to Break Free',
      'Keep Passing the Open Windows',
      'Hammer to Fall',
      'Is This the World We Created…?',
    ],
  },
  {
    id: 'still-fantasy',
    title: '依然范特西',
    artist: '周杰倫',
    year: 2006,
    edition: '阿爾發音樂 · CD',
    cover: '/albums/still-fantasy.jpg',
    accent: '#9b856e',
    tracks: [
      { title: '夜的第七章', artist: '周杰倫、潘兒' },
      '聽媽媽的話',
      { title: '千里之外', artist: '周杰倫、費玉清' },
      '本草綱目',
      '退後',
      '紅模仿',
      '心雨',
      '白色風車',
      '迷迭香',
      '菊花台',
    ],
  },
  {
    id: 'a-dream-return-to-tang-dynasty',
    title: '夢回唐朝',
    artist: '唐朝樂隊',
    year: 1992,
    edition: '魔岩唱片 · CD',
    cover: '/albums/a-dream-return-to-tang-dynasty.webp',
    accent: '#bd202b',
    tracks: [
      '夢回唐朝',
      '太陽',
      '九拍',
      '天堂',
      '選擇',
      '飛翔鳥',
      '世紀末之夢',
      '月夢',
      '不要逃避',
      '傳說',
      '國際歌',
    ],
  },
  {
    id: 'garbage-dump',
    title: '垃圾場',
    artist: '何勇',
    year: 1994,
    edition: '魔岩唱片 · CD',
    cover: '/albums/garbage-dump.jpg',
    accent: '#e04a23',
    tracks: [
      '垃圾場',
      '姑娘 漂亮',
      '頭上的包',
      '聊天',
      '踏步',
      '鐘鼓樓',
      '冬眠',
      '非洲夢',
      '幽靈',
      '垃圾場 (二版)',
    ],
  },
  {
    id: 'shameful-being-left-alone',
    title: '孤獨的人是可恥的',
    artist: '張楚',
    year: 1994,
    edition: '魔岩唱片 · CD',
    cover: '/albums/shameful-being-left-alone.jpg',
    accent: '#62554b',
    tracks: [
      '上蒼保佑吃完了飯的人民',
      '冷暖自知',
      '螞蟻螞蟻',
      '和大夥兒去乘涼',
      '愛情',
      '孤獨的人是可恥的',
      '蒼蠅',
      '趙小姐',
      '廁所和床',
      '光明大道',
    ],
  },
  {
    id: 'home-1984',
    title: '家',
    artist: '羅大佑',
    year: 1984,
    edition: '滾石唱片 · LP',
    cover: '/albums/home-1984.jpg',
    accent: '#bd703d',
    tracks: [
      '吾鄉印象',
      '家 (I)',
      '超級市民',
      '青蚵嫂',
      '家 (II)',
      '我所不能瞭解的事',
      '穿過你的黑髮的我的手',
      'Mysterious Eyes',
      '耶穌的另一個名字',
    ],
  },
  {
    id: 'comrade-lover',
    title: '愛人同志',
    artist: '羅大佑',
    year: 1988,
    edition: '滾石唱片 · CD',
    cover: '/albums/comrade-lover.jpg',
    accent: '#a82b2a',
    tracks: [
      '暗戀',
      '戀曲1990',
      '愛人同志',
      '你的樣子',
      '夢',
      '黃色臉孔',
      '京城夜',
      '明天的太陽',
      '遊戲規則',
      '不變的結局',
    ],
  },
  {
    id: 'rock-on-new-long-march',
    title: '新長征路上的搖滾',
    artist: '崔健',
    year: 1989,
    edition: '中國旅遊聲像 · CD',
    cover: '/albums/rock-on-new-long-march.jpg',
    accent: '#cf2028',
    tracks: [
      '新長征路上的搖滾',
      '不再掩飾',
      '讓我睡個好覺',
      '花房姑娘',
      '假行僧',
      '從頭再來',
      '出走',
      '一無所有',
      '不是我不明白',
    ],
  },
  {
    id: 'time-walk',
    title: '時光·漫步',
    artist: '許巍',
    year: 2002,
    edition: '步升大風 · CD',
    cover: '/albums/time-walk.jpg',
    accent: '#7994a6',
    tracks: [
      '天鵝之旅',
      '完美生活',
      '時光',
      '藍蓮花',
      '一天',
      '禮物',
      '漫步',
      '星空',
      '夏日的風',
      '平淡',
    ],
  },
  {
    id: 'balls-under-the-red-flag',
    title: '紅旗下的蛋',
    artist: '崔健',
    year: 1994,
    edition: 'EMI百代 · CD',
    cover: '/albums/balls-under-the-red-flag.jpg',
    accent: '#c5262d',
    tracks: [
      '飛了',
      '寬容',
      '紅旗下的蛋',
      '北京的故事',
      '盒子',
      '最後的抱怨',
      '誤會',
      '彼岸',
    ],
  },
  {
    id: 'naked',
    title: '赤裸裸',
    artist: '鄭鈞',
    year: 1994,
    edition: '紅星生產社 · CD',
    cover: '/albums/naked.jpg',
    accent: '#b7262f',
    tracks: [
      '回到拉薩',
      '幸福可望不可及',
      '極樂世界',
      '赤裸裸 (鄉搖版)',
      '灰姑娘',
      '商品社會',
      '牌坊',
      '茫然',
      '難得糊塗',
      '無為',
      '赤裸裸 (搖滾版)',
    ],
  },
  {
    id: 'lifes-a-struggle',
    title: "Life's a Struggle",
    artist: '宋岳庭',
    year: 2003,
    edition: '原動力 · CD',
    cover: '/albums/lifes-a-struggle.jpg',
    accent: '#c8762f',
    tracks: [
      'Intro',
      'Live From L.A.',
      'Trigger Effect',
      'Love Song',
      '太陽照在你臉上',
      'Yeah',
      'Taiwan Pop Sucks 2000',
      '怎麼辦',
      'Shang Guh',
      'Beat From A Dusty Box',
      '好無聊',
      'Crum 6',
      "Life's a Struggle",
      'Interlude',
      'Day Dream',
      'Outro',
      "Life's a Struggle (Remix)",
      '讓我自己飛',
      'Toy Story',
    ],
  },
  {
    id: 'liehu-xingzuo',
    title: '猎户星座',
    artist: '朴树',
    year: 2017,
    edition: '五大唱片 · CD',
    cover: '/albums/liehu-xingzuo.jpg',
    accent: '#2e8a7d',
    tracks: [
      '空帆船',
      'Never Knows Tomorrow',
      '在木星',
      '好好地',
      'XX青春',
      'Baby，До свидания',
      '吉他演奏曲',
      'No Fear In My Heart',
      'Forever Young',
      '平凡之路',
      '清白之年',
      '猎户星座',
    ],
  },
]
