// Keep the collection in one place. Add a local image under public/albums and
// set `cover` to (for example) '/albums/xingfu-de-pangbian.jpg' when available.
export const ALBUMS = [
  {
    id: 'xingfu-de-pangbian',
    title: '幸福的旁边',
    artist: '花儿乐队',
    year: 1999,
    edition: '新蜂音乐 · CD',
    cover: '/albums/xingfu-de-pangbian.jpg',
    accent: '#e63946',
    tracks: [
      '轰隆隆',
      '花',
      '四季歌 (新蜂版)',
      '向我开炮',
      '静止',
      '破灭',
      '起飞',
      '幸福的旁边',
      '稻草上的火鸡',
      '结果',
      '别骗我 (DEMO)',
      '融化',
      '没辙',
      '花 (木吉他版)',
      '放学啦 (新蜂版)',
      '歌唱 (CD版附送曲)',
    ],
  },
  {
    id: 'zhi-hu-zhe-ye',
    title: '之乎者也',
    artist: '羅大佑',
    year: 1982,
    edition: '滾石唱片 · LP',
    cover: '/albums/zhi-hu-zhe-ye.jpg',
    accent: '#c92328',
    tracks: [
      '鹿港小鎮',
      '戀曲1980',
      '童年',
      '錯誤',
      '搖籃曲',
      '之乎者也',
      '鄉愁四韻',
      '將進酒',
      '光陰的故事',
      '蒲公英',
    ],
  },
]
