// Keep the collection in one place. Add a local image under public/albums and
// set `cover` to (for example) '/albums/xingfu-de-pangbian.jpg' when available.
export const ALBUMS = [
  {
    id: 'xingfu-de-pangbian',
    title: '幸福的旁边',
    artist: '花儿乐队',
    year: 1999,
    edition: '新蜂音乐 · CD',
    cover: '/albums/xingfu-de-pangbian.jpg',
    accent: '#e63946',
    tracks: [
      '轰隆隆',
      '花',
      '四季歌 (新蜂版)',
      '向我开炮',
      '静止',
      '破灭',
      '起飞',
      '幸福的旁边',
      '稻草上的火鸡',
      '结果',
      '别骗我 (DEMO)',
      '融化',
      '没辙',
      '花 (木吉他版)',
      '放学啦 (新蜂版)',
      '歌唱 (CD版附送曲)',
    ],
  },
  {
    id: 'zhi-hu-zhe-ye',
    title: '之乎者也',
    artist: '羅大佑',
    year: 1982,
    edition: '滾石唱片 · LP',
    cover: '/albums/zhi-hu-zhe-ye.jpg',
    accent: '#c92328',
    tracks: [
      '鹿港小鎮',
      '戀曲1980',
      '童年',
      '錯誤',
      '搖籃曲',
      '之乎者也',
      '鄉愁四韻',
      '將進酒',
      '光陰的故事',
      '蒲公英',
    ],
  },
  {
    id: 'weilai-de-zhurenweng',
    title: '未來的主人翁',
    artist: '羅大佑',
    year: 1983,
    edition: '滾石唱片 · LP',
    cover: '/albums/weilai-de-zhurenweng.jpg',
    accent: '#afb58a',
    tracks: [
      '誕生',
      '亞細亞的孤兒',
      '現象七十二變',
      '牧童',
      '未來的主人翁',
      '青春舞曲',
      '愛的箴言',
      '小妹',
      '盲聾',
      '稻草人',
    ],
  },
  {
    id: 'queens-road-east',
    title: '皇后大道東',
    artist: '群星 · 音樂工廠',
    year: 1991,
    edition: '音樂工廠 · CD',
    cover: '/albums/queens-road-east.jpg',
    accent: '#b75939',
    tracks: [
      { title: '皇后大道東', artist: '羅大佑、蔣志光' },
      { title: '情深義更深', artist: '袁鳳瑫' },
      { title: '出走', artist: '夏韶聲' },
      { title: '赤子', artist: '葉德嫻' },
      { title: '長路有多遠', artist: '蔣志光' },
      { title: '似是故人來', artist: '梅艷芳' },
      { title: '天若有情', artist: '袁鳳瑫' },
      { title: '道', artist: '黃霅' },
      { title: '青春舞曲2000', artist: '羅大佑' },
      { title: '東方之珠', artist: '羅大佑' },
    ],
  },
  {
    id: 'hei-bao',
    title: '黑豹',
    artist: '黑豹樂隊',
    year: 1991,
    edition: '滾石唱片 · CD',
    cover: '/albums/hei-bao.jpg',
    accent: '#e25326',
    tracks: [
      '無地自容',
      'Take Care',
      '體會',
      '別來糾纏我',
      '靠近我',
      "Don't Break My Heart",
      '臉譜',
      '怕你為自己流淚',
      '眼光裡',
      '別去糟蹋',
    ],
  },
  {
    id: 'rock-china-power',
    title: '搖滾中國樂勢力',
    artist: '群星',
    year: 1995,
    edition: '魔岩唱片 · Live CD',
    cover: '/albums/rock-china-power.jpg',
    accent: '#e44b2d',
    tracks: [
      { title: '噢 乖', artist: '竇唯' },
      { title: '高級動物 (Live)', artist: '竇唯' },
      { title: '悲傷的夢 (Live)', artist: '竇唯' },
      { title: '飛翔鳥 (Live)', artist: '唐朝樂隊' },
      { title: '選擇 (Live)', artist: '唐朝樂隊' },
      { title: '孤獨的人是可恥的 (Live)', artist: '張楚' },
      { title: '廁所和床 (Live)', artist: '張楚' },
      { title: '蟞蟻 蟞蟻 (Live)', artist: '張楚' },
      { title: '姑娘 漂亮 (Live)', artist: '何勇' },
      { title: '鐘鼓樓 (Live)', artist: '何勇' },
    ],
  },
  {
    id: 'a-night-at-the-opera',
    title: 'A Night at the Opera',
    artist: 'Queen',
    year: 1975,
    edition: 'EMI · LP',
    cover: '/albums/a-night-at-the-opera.jpg',
    accent: '#8e1f2f',
    tracks: [
      'Death on Two Legs (Dedicated to…)',
      'Lazing on a Sunday Afternoon',
      "I'm in Love with My Car",
      "You're My Best Friend",
      "'39",
      'Sweet Lady',
      'Seaside Rendezvous',
      "The Prophet's Song",
      'Love of My Life',
      'Good Company',
      'Bohemian Rhapsody',
      'God Save the Queen',
    ],
  },
  {
    id: 'the-works',
    title: 'The Works',
    artist: 'Queen',
    year: 1984,
    edition: 'EMI · LP',
    cover: '/albums/the-works.jpg',
    accent: '#a51d25',
    tracks: [
      'Radio Ga Ga',
      'Tear It Up',
      "It's a Hard Life",
      'Man on the Prowl',
      "Machines (or 'Back to Humans')",
      'I Want to Break Free',
      'Keep Passing the Open Windows',
      'Hammer to Fall',
      'Is This the World We Created…?',
    ],
  },
  {
    id: 'still-fantasy',
    title: '依然范特西',
    artist: '周杰倫',
    year: 2006,
    edition: '阿爾發音樂 · CD',
    cover: '/albums/still-fantasy.jpg',
    accent: '#9b856e',
    tracks: [
      { title: '夜的第七章', artist: '周杰倫、潘兒' },
      '聽媽媽的話',
      { title: '千里之外', artist: '周杰倫、費玉清' },
      '本草綱目',
      '退後',
      '紅模仿',
      '心雨',
      '白色風車',
      '迷迭香',
      '菊花台',
    ],
  },
]
